name: haba
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^1.1.6
  http: ^0.13.5
  cached_network_image: ^3.2.3
  shared_preferences: ^2.0.15
  easy_localization: ^3.0.1
  url_launcher: ^6.1.10
  flutter_phone_direct_caller: ^2.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

